//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreWebForms.CartService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService.Entities")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookstoreWebForms.CartService.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookID {
            get {
                return this.BookIDField;
            }
            set {
                if ((this.BookIDField.Equals(value) != true)) {
                    this.BookIDField = value;
                    this.RaisePropertyChanged("BookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookstoreWebForms.CartService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Cover {
            get {
                return this.CoverField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverField, value) != true)) {
                    this.CoverField = value;
                    this.RaisePropertyChanged("Cover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService.Entities")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookstoreWebForms.CartService.Book[] BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookstoreWebForms.CartService.Book[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalBook", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService.Entities")]
    [System.SerializableAttribute()]
    public partial class ExternalBook : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService.Entities")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookstoreWebForms.CartService.CartBook[] BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookstoreWebForms.CartService.DeliveryOption DeliveryOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliveryOptionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookstoreWebForms.CartService.PaymentMethod PaymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PaymentMethodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookstoreWebForms.CartService.CartBook[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookstoreWebForms.CartService.DeliveryOption DeliveryOption {
            get {
                return this.DeliveryOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryOptionField, value) != true)) {
                    this.DeliveryOptionField = value;
                    this.RaisePropertyChanged("DeliveryOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryOptionID {
            get {
                return this.DeliveryOptionIDField;
            }
            set {
                if ((this.DeliveryOptionIDField.Equals(value) != true)) {
                    this.DeliveryOptionIDField = value;
                    this.RaisePropertyChanged("DeliveryOptionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPaid {
            get {
                return this.IsPaidField;
            }
            set {
                if ((this.IsPaidField.Equals(value) != true)) {
                    this.IsPaidField = value;
                    this.RaisePropertyChanged("IsPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModification {
            get {
                return this.LastModificationField;
            }
            set {
                if ((this.LastModificationField.Equals(value) != true)) {
                    this.LastModificationField = value;
                    this.RaisePropertyChanged("LastModification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookstoreWebForms.CartService.PaymentMethod PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentMethodField, value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaymentMethodID {
            get {
                return this.PaymentMethodIDField;
            }
            set {
                if ((this.PaymentMethodIDField.Equals(value) != true)) {
                    this.PaymentMethodIDField = value;
                    this.RaisePropertyChanged("PaymentMethodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryOption", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryOption : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeliveryOptionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeliveryOptionID {
            get {
                return this.DeliveryOptionIDField;
            }
            set {
                if ((this.DeliveryOptionIDField.Equals(value) != true)) {
                    this.DeliveryOptionIDField = value;
                    this.RaisePropertyChanged("DeliveryOptionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentMethod", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService.Entities")]
    [System.SerializableAttribute()]
    public partial class PaymentMethod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentMethodIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentMethodID {
            get {
                return this.PaymentMethodIDField;
            }
            set {
                if ((this.PaymentMethodIDField.Equals(value) != true)) {
                    this.PaymentMethodIDField = value;
                    this.RaisePropertyChanged("PaymentMethodID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartBook", Namespace="http://schemas.datacontract.org/2004/07/BookstoreService.Entities")]
    [System.SerializableAttribute()]
    public partial class CartBook : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AddedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookstoreWebForms.CartService.Book BookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AddedOn {
            get {
                return this.AddedOnField;
            }
            set {
                if ((this.AddedOnField.Equals(value) != true)) {
                    this.AddedOnField = value;
                    this.RaisePropertyChanged("AddedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookstoreWebForms.CartService.Book Book {
            get {
                return this.BookField;
            }
            set {
                if ((object.ReferenceEquals(this.BookField, value) != true)) {
                    this.BookField = value;
                    this.RaisePropertyChanged("Book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookID {
            get {
                return this.BookIDField;
            }
            set {
                if ((this.BookIDField.Equals(value) != true)) {
                    this.BookIDField = value;
                    this.RaisePropertyChanged("BookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://unwe.bg", ConfigurationName="CartService.IBooksService")]
    public interface IBooksService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetAllBooks", ReplyAction="http://unwe.bg/IBooksService/GetAllBooksResponse")]
        BookstoreWebForms.CartService.Book[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetAllBooks", ReplyAction="http://unwe.bg/IBooksService/GetAllBooksResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetAllCategories", ReplyAction="http://unwe.bg/IBooksService/GetAllCategoriesResponse")]
        BookstoreWebForms.CartService.Category[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetAllCategories", ReplyAction="http://unwe.bg/IBooksService/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Category[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetBooksByCategoryId", ReplyAction="http://unwe.bg/IBooksService/GetBooksByCategoryIdResponse")]
        BookstoreWebForms.CartService.Book[] GetBooksByCategoryId(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetBooksByCategoryId", ReplyAction="http://unwe.bg/IBooksService/GetBooksByCategoryIdResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book[]> GetBooksByCategoryIdAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetBooksByCategory", ReplyAction="http://unwe.bg/IBooksService/GetBooksByCategoryResponse")]
        BookstoreWebForms.CartService.Book[] GetBooksByCategory(BookstoreWebForms.CartService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetBooksByCategory", ReplyAction="http://unwe.bg/IBooksService/GetBooksByCategoryResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book[]> GetBooksByCategoryAsync(BookstoreWebForms.CartService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetBook", ReplyAction="http://unwe.bg/IBooksService/GetBookResponse")]
        BookstoreWebForms.CartService.Book GetBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetBook", ReplyAction="http://unwe.bg/IBooksService/GetBookResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book> GetBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetBookByISBN", ReplyAction="http://unwe.bg/IBooksService/GetBookByISBNResponse")]
        BookstoreWebForms.CartService.Book GetBookByISBN(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetBookByISBN", ReplyAction="http://unwe.bg/IBooksService/GetBookByISBNResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book> GetBookByISBNAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetSimilarBooks", ReplyAction="http://unwe.bg/IBooksService/GetSimilarBooksResponse")]
        BookstoreWebForms.CartService.ExternalBook[] GetSimilarBooks(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/GetSimilarBooks", ReplyAction="http://unwe.bg/IBooksService/GetSimilarBooksResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.ExternalBook[]> GetSimilarBooksAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/CreateBook", ReplyAction="http://unwe.bg/IBooksService/CreateBookResponse")]
        BookstoreWebForms.CartService.Book CreateBook(BookstoreWebForms.CartService.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/CreateBook", ReplyAction="http://unwe.bg/IBooksService/CreateBookResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book> CreateBookAsync(BookstoreWebForms.CartService.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/UpdateBook", ReplyAction="http://unwe.bg/IBooksService/UpdateBookResponse")]
        BookstoreWebForms.CartService.Book UpdateBook(BookstoreWebForms.CartService.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/UpdateBook", ReplyAction="http://unwe.bg/IBooksService/UpdateBookResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book> UpdateBookAsync(BookstoreWebForms.CartService.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/RemoveBook", ReplyAction="http://unwe.bg/IBooksService/RemoveBookResponse")]
        void RemoveBook(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/IBooksService/RemoveBook", ReplyAction="http://unwe.bg/IBooksService/RemoveBookResponse")]
        System.Threading.Tasks.Task RemoveBookAsync(int bookId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBooksServiceChannel : BookstoreWebForms.CartService.IBooksService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BooksServiceClient : System.ServiceModel.ClientBase<BookstoreWebForms.CartService.IBooksService>, BookstoreWebForms.CartService.IBooksService {
        
        public BooksServiceClient() {
        }
        
        public BooksServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BooksServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookstoreWebForms.CartService.Book[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public BookstoreWebForms.CartService.Category[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Category[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public BookstoreWebForms.CartService.Book[] GetBooksByCategoryId(int categoryId) {
            return base.Channel.GetBooksByCategoryId(categoryId);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book[]> GetBooksByCategoryIdAsync(int categoryId) {
            return base.Channel.GetBooksByCategoryIdAsync(categoryId);
        }
        
        public BookstoreWebForms.CartService.Book[] GetBooksByCategory(BookstoreWebForms.CartService.Category category) {
            return base.Channel.GetBooksByCategory(category);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book[]> GetBooksByCategoryAsync(BookstoreWebForms.CartService.Category category) {
            return base.Channel.GetBooksByCategoryAsync(category);
        }
        
        public BookstoreWebForms.CartService.Book GetBook(int id) {
            return base.Channel.GetBook(id);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book> GetBookAsync(int id) {
            return base.Channel.GetBookAsync(id);
        }
        
        public BookstoreWebForms.CartService.Book GetBookByISBN(string isbn) {
            return base.Channel.GetBookByISBN(isbn);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book> GetBookByISBNAsync(string isbn) {
            return base.Channel.GetBookByISBNAsync(isbn);
        }
        
        public BookstoreWebForms.CartService.ExternalBook[] GetSimilarBooks(int id) {
            return base.Channel.GetSimilarBooks(id);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.ExternalBook[]> GetSimilarBooksAsync(int id) {
            return base.Channel.GetSimilarBooksAsync(id);
        }
        
        public BookstoreWebForms.CartService.Book CreateBook(BookstoreWebForms.CartService.Book book) {
            return base.Channel.CreateBook(book);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book> CreateBookAsync(BookstoreWebForms.CartService.Book book) {
            return base.Channel.CreateBookAsync(book);
        }
        
        public BookstoreWebForms.CartService.Book UpdateBook(BookstoreWebForms.CartService.Book book) {
            return base.Channel.UpdateBook(book);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Book> UpdateBookAsync(BookstoreWebForms.CartService.Book book) {
            return base.Channel.UpdateBookAsync(book);
        }
        
        public void RemoveBook(int bookId) {
            base.Channel.RemoveBook(bookId);
        }
        
        public System.Threading.Tasks.Task RemoveBookAsync(int bookId) {
            return base.Channel.RemoveBookAsync(bookId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://unwe.bg", ConfigurationName="CartService.ICartService")]
    public interface ICartService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/CreateCart", ReplyAction="http://unwe.bg/ICartService/CreateCartResponse")]
        BookstoreWebForms.CartService.Cart CreateCart(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/CreateCart", ReplyAction="http://unwe.bg/ICartService/CreateCartResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Cart> CreateCartAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/AddToCart", ReplyAction="http://unwe.bg/ICartService/AddToCartResponse")]
        bool AddToCart(int cartId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/AddToCart", ReplyAction="http://unwe.bg/ICartService/AddToCartResponse")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(int cartId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/GetCart", ReplyAction="http://unwe.bg/ICartService/GetCartResponse")]
        BookstoreWebForms.CartService.Cart GetCart(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/GetCart", ReplyAction="http://unwe.bg/ICartService/GetCartResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.Cart> GetCartAsync(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/RemoveFromCart", ReplyAction="http://unwe.bg/ICartService/RemoveFromCartResponse")]
        bool RemoveFromCart(int cartId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/RemoveFromCart", ReplyAction="http://unwe.bg/ICartService/RemoveFromCartResponse")]
        System.Threading.Tasks.Task<bool> RemoveFromCartAsync(int cartId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/SetPaymentMethod", ReplyAction="http://unwe.bg/ICartService/SetPaymentMethodResponse")]
        bool SetPaymentMethod(int cartId, BookstoreWebForms.CartService.PaymentMethod method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/SetPaymentMethod", ReplyAction="http://unwe.bg/ICartService/SetPaymentMethodResponse")]
        System.Threading.Tasks.Task<bool> SetPaymentMethodAsync(int cartId, BookstoreWebForms.CartService.PaymentMethod method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/SetDeliveryOptions", ReplyAction="http://unwe.bg/ICartService/SetDeliveryOptionsResponse")]
        bool SetDeliveryOptions(int cartId, BookstoreWebForms.CartService.DeliveryOption options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/SetDeliveryOptions", ReplyAction="http://unwe.bg/ICartService/SetDeliveryOptionsResponse")]
        System.Threading.Tasks.Task<bool> SetDeliveryOptionsAsync(int cartId, BookstoreWebForms.CartService.DeliveryOption options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/Purchase", ReplyAction="http://unwe.bg/ICartService/PurchaseResponse")]
        bool Purchase(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/Purchase", ReplyAction="http://unwe.bg/ICartService/PurchaseResponse")]
        System.Threading.Tasks.Task<bool> PurchaseAsync(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/GetDeliveryOptions", ReplyAction="http://unwe.bg/ICartService/GetDeliveryOptionsResponse")]
        BookstoreWebForms.CartService.DeliveryOption[] GetDeliveryOptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/GetDeliveryOptions", ReplyAction="http://unwe.bg/ICartService/GetDeliveryOptionsResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.DeliveryOption[]> GetDeliveryOptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/GetPaymentMethods", ReplyAction="http://unwe.bg/ICartService/GetPaymentMethodsResponse")]
        BookstoreWebForms.CartService.PaymentMethod[] GetPaymentMethods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unwe.bg/ICartService/GetPaymentMethods", ReplyAction="http://unwe.bg/ICartService/GetPaymentMethodsResponse")]
        System.Threading.Tasks.Task<BookstoreWebForms.CartService.PaymentMethod[]> GetPaymentMethodsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICartServiceChannel : BookstoreWebForms.CartService.ICartService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CartServiceClient : System.ServiceModel.ClientBase<BookstoreWebForms.CartService.ICartService>, BookstoreWebForms.CartService.ICartService {
        
        public CartServiceClient() {
        }
        
        public CartServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CartServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookstoreWebForms.CartService.Cart CreateCart(string userId) {
            return base.Channel.CreateCart(userId);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Cart> CreateCartAsync(string userId) {
            return base.Channel.CreateCartAsync(userId);
        }
        
        public bool AddToCart(int cartId, int bookId) {
            return base.Channel.AddToCart(cartId, bookId);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(int cartId, int bookId) {
            return base.Channel.AddToCartAsync(cartId, bookId);
        }
        
        public BookstoreWebForms.CartService.Cart GetCart(int cartId) {
            return base.Channel.GetCart(cartId);
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.Cart> GetCartAsync(int cartId) {
            return base.Channel.GetCartAsync(cartId);
        }
        
        public bool RemoveFromCart(int cartId, int bookId) {
            return base.Channel.RemoveFromCart(cartId, bookId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFromCartAsync(int cartId, int bookId) {
            return base.Channel.RemoveFromCartAsync(cartId, bookId);
        }
        
        public bool SetPaymentMethod(int cartId, BookstoreWebForms.CartService.PaymentMethod method) {
            return base.Channel.SetPaymentMethod(cartId, method);
        }
        
        public System.Threading.Tasks.Task<bool> SetPaymentMethodAsync(int cartId, BookstoreWebForms.CartService.PaymentMethod method) {
            return base.Channel.SetPaymentMethodAsync(cartId, method);
        }
        
        public bool SetDeliveryOptions(int cartId, BookstoreWebForms.CartService.DeliveryOption options) {
            return base.Channel.SetDeliveryOptions(cartId, options);
        }
        
        public System.Threading.Tasks.Task<bool> SetDeliveryOptionsAsync(int cartId, BookstoreWebForms.CartService.DeliveryOption options) {
            return base.Channel.SetDeliveryOptionsAsync(cartId, options);
        }
        
        public bool Purchase(int cartId) {
            return base.Channel.Purchase(cartId);
        }
        
        public System.Threading.Tasks.Task<bool> PurchaseAsync(int cartId) {
            return base.Channel.PurchaseAsync(cartId);
        }
        
        public BookstoreWebForms.CartService.DeliveryOption[] GetDeliveryOptions() {
            return base.Channel.GetDeliveryOptions();
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.DeliveryOption[]> GetDeliveryOptionsAsync() {
            return base.Channel.GetDeliveryOptionsAsync();
        }
        
        public BookstoreWebForms.CartService.PaymentMethod[] GetPaymentMethods() {
            return base.Channel.GetPaymentMethods();
        }
        
        public System.Threading.Tasks.Task<BookstoreWebForms.CartService.PaymentMethod[]> GetPaymentMethodsAsync() {
            return base.Channel.GetPaymentMethodsAsync();
        }
    }
}
